server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mentoring
    username: "root"
    password: "tndls4343"
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    # create:  DB에 이는 것 전부 초기화
    # update: DB에 잇는 거에서 계속 업데이트
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: false
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher # about swagger

